spring.profiles.active=prod
management.endpoints.web.exposure.include=*
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8083/realms/specmatic
spring.security.oauth2.resourceserver.jwt.audiences=order-api
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=${SERVER_SSL_KEY_STORE:file:certs/server-keystore.jks}
server.ssl.key-store-type=JKS
server.ssl.key-store-password=${SERVER_SSL_KEY_STORE_PASSWORD:changeit}
server.ssl.key-alias=order-api
server.ssl.key-password=${SERVER_SSL_KEY_PASSWORD:changeit}
server.ssl.trust-store=${SERVER_SSL_TRUST_STORE:file:certs/server-truststore.jks}
server.ssl.trust-store-type=JKS
server.ssl.trust-store-password=${SERVER_SSL_TRUST_STORE_PASSWORD:changeit}
server.ssl.client-auth=need
